-- ==============================================================================
-- EKMEKLAB INITIAL SEED DATA FOR SUPABASE
-- ==============================================================================

-- 1. CATEGORIES
INSERT INTO public.categories (id, name, description, display_order)
VALUES
    ('bread', 'Taş Fırın Ekmeklerimiz', 'Geleneksel taş fırında meşe odunu buharıyla pişirilen günlük taze ekşi mayalı ekmekler.', 1),
    ('specialty', 'Özel & Ön Sipariş', 'Kavrulmuş kuruyemişli, dağ meyveli ve kadim tahıllı imza artisan reçetelerimiz.', 2),
    ('gurme', 'Gurme & Mandıra Eşlikçileri', 'Jersey çiğ sütü, ev yoğurdu, hakiki Mihaliç peyniri ve doğal şarküteri lezzetleri.', 3)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    display_order = EXCLUDED.display_order;

-- 2. PRODUCTS
INSERT INTO public.products (
    id, name, slug, description, price, image_url, category, stock, weight, weight_unit,
    made_to_order, is_popular, is_new, is_available, is_active, ingredients, flour_types, hydration, masterclass
)
VALUES
(
    'sample-ekmek-1',
    'Taş Fırın Ekşi Mayalı Köy Ekmeği',
    'tas-firin-eksi-mayali-koy-ekmegi',
    'Taş değirmen atalık unlar, içme suyu, Çankırı kaya tuzu ve 8 yıllık canlı ekşi maya. 36 saatlik geleneksel soğuk fermantasyonla her gün taze pişer.',
    150,
    'https://firebasestorage.googleapis.com/v0/b/eksimayaliekmekweb.firebasestorage.app/o/product-images%2Fsample-ekmek-1%2F1766242431736_whatsapp_image_2025-12-19_at_18.44.09.jpeg.jpg?alt=media&token=e2c0a40d-5912-4387-8fb1-8ab39616fc6c',
    'bread',
    45,
    800,
    'g',
    false,
    true,
    false,
    true,
    true,
    '["Taş Değirmen Atalık Un", "Su", "8 Yıllık Ekşi Maya", "Çankırı Kaya Tuzu"]'::jsonb,
    '["Taş Değirmen Atalık Buğday", "Karakılçık"]'::jsonb,
    76,
    '{"flourHeritage": "Taş değirmende ruşeymi ve kepeği ayrıştırılmadan öğütülen yerli atalık buğdaylar kullanılır. 8 yıldır beslediğimiz ekşi mayamızla harmanlanır.", "technique": "%76 hidrasyonla yoğrulur. Hamur teknelerinde 30 dakikada bir lamine katlama uygulanır. Şekillendirildikten sonra 36 saat boyunca +4°C soğuk fermantasyon geçirir.", "healthBenefit": "Doğal laktik asit fermantasyonu tahıldaki fitik asidi parçalar, gluten zincirlerini yumuşatır; asla şişkinlik yapmaz, sindirimi son derece rahattır.", "pairingStorage": "Bez torba içinde oda sıcaklığında 5 gün tazeliğini korur. Dilimleyip dondurabilirsiniz. Tost yapıldığında çıtır kabuğuyla benzersiz bir lezzet sunar."}'::jsonb
),
(
    'prod_karakilcik_01',
    '%100 Karakılçık Ekşi Mayalı',
    'yuzde-yuz-karakilcik-eksi-mayali',
    'Genetiği bozulmamış ata tohumu Gediz Karakılçık buğdayı, canlı ekşi maya, su ve kaya tuzu. 36 saat soğuk fermantasyonla demlenir; her gün taze pişer.',
    145,
    'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85',
    'bread',
    40,
    850,
    'g',
    false,
    true,
    false,
    true,
    true,
    '["Karakılçık Tam Buğday Unu", "Su", "8 Yıllık Canlı Ekşi Maya", "Çankırı Kaya Tuzu"]'::jsonb,
    '["Gediz Karakılçık Tam Buğday"]'::jsonb,
    78,
    '{"flourHeritage": "Ege yöresinin atalık Karakılçık buğdayı taş değirmende ruşeymi ayrıştırılmadan öğütülür. Yoğun kehribar rengi ve fındıksı lezzeti buradan gelir.", "technique": "%78 yüksek su oranıyla narin yoğrulur. Taş fırının taban sıcağında meşe odunu buharıyla pişirilir.", "healthBenefit": "Yüksek antioksidan, çinko, demir ve lif içeriğine sahiptir. Kan şekerini dengeli yükseltir ve saatlerce tok tutar.", "pairingStorage": "Oda sıcaklığında 5 gün tazedir. Tavada hafifçe ısıtıp köy tereyağı ve Mihaliç peyniri ile tüketmeniz tavsiye edilir."}'::jsonb
),
(
    'eseWoYLrSinWrP2VGOmW',
    '%100 Taş Değirmen Siyez Ekmeği',
    'yuzde-yuz-tas-degirmen-siyez-ekmegi',
    'Kastamonu İhsangazi siyezi ve canlı ekşi maya ile 40 saatlik uzun fermentasyon süreciyle hazırlanır. Düşük glutenli, zengin mineralli.',
    200,
    'https://firebasestorage.googleapis.com/v0/b/eksimayaliekmekweb.firebasestorage.app/o/product-images%2FeseWoYLrSinWrP2VGOmW%2F1766243754267_d3d13c14-ed8a-4d37-a65d-aba92e1cafe0.png.jpg?alt=media&token=61e7044d-f693-4120-bd50-b8dc29695425',
    'bread',
    30,
    1000,
    'g',
    false,
    true,
    false,
    true,
    true,
    '["Kastamonu Siyez Unu", "İçme Suyu", "Canlı Ekşi Maya", "Kaya Tuzu"]'::jsonb,
    '["Kastamonu Atalık Siyez"]'::jsonb,
    78,
    '{"flourHeritage": "12.000 yıllık geçmişiyle dünyanın ilk buğdayı olan tek başaklı atalık Siyez buğdayı.", "technique": "Siyezin narin gluten yapısını bozmamak için makine yerine elle katlanır. 40 saatlik soğuk fermantasyonla olgunlaştırılır.", "healthBenefit": "A, B ve E vitaminleri, çinko, demir ve lutein deposudur. Düşük gluten indeksi sayesinde hassas mideler için en dost ekmektir.", "pairingStorage": "Yoğun ve nemli bir iç yapıya sahiptir. Dilimlendiğinde günlerce kurumaz."}'::jsonb
),
(
    'prod_yudane_03',
    'Japon Yudane Sütlü Tost Ekmeği',
    'japon-yudane-sutlu-tost-ekmegi',
    'Yudane haşlama hamur tekniğiyle kaynar suyla jelatinize edilmiş un bazlı. Pamuksu iç doku, 5 gün boyunca tazeliğini koruyan doğal nemlilik.',
    130,
    'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=900&q=85',
    'bread',
    25,
    650,
    'g',
    false,
    true,
    false,
    true,
    true,
    '["Yüksek Proteinli Un", "Yudane Hamuru", "Taze Süt", "Köy Tereyağı", "Ekşi Maya", "Tuz"]'::jsonb,
    '["Taş Değirmen Ekmeklik Un"]'::jsonb,
    75,
    '{"flourHeritage": "Geleneksel Japon Yudane tekniği: Unun bir kısmı kaynar su ile önceden demlenerek nişastası jelatinize edilir.", "technique": "Jelatinleşen hamur, su tutma kapasitesini 2 katına çıkarır. İçine süt ve köy tereyağı eklenerek ipeksi bir doku elde edilir.", "healthBenefit": "Hiçbir ticari koruyucu, emülgatör veya katkı olmadan tamamen doğal fiziksel yöntemle 5 gün boyunca pamuk gibi yumuşak kalır.", "pairingStorage": "Tost makinesinde dışı çıtır, içi yumuşacık kabarır. Çocuklar ve gurme tost sevenler için idealdir."}'::jsonb
),
(
    'sample-ekmek-2',
    'EkmekLab Özel (Cevizli Çok Tahıllı)',
    'ekmeklab-ozel-cevizli-cok-tahilli',
    'Taş fırında kavrulmuş yerli ceviz içi, siyez, karabuğday ve çavdar unlarının dengeli harmanıyla üretilen imza artisan ekşi mayalı.',
    250,
    'https://firebasestorage.googleapis.com/v0/b/eksimayaliekmekweb.firebasestorage.app/o/product-images%2Fsample-ekmek-2%2F1766243701366_unnamed_8_.jpg.jpg?alt=media&token=e55d6ee5-95fb-45ca-8771-a2e6624405c2',
    'specialty',
    20,
    850,
    'g',
    true,
    true,
    false,
    true,
    true,
    '["Kavrulmuş Ceviz İçi", "Siyez Unu", "Karabuğday Unu", "Çavdar Unu", "Su", "Ekşi Maya", "Kaya Tuzu"]'::jsonb,
    '["Siyez", "Karabuğday", "Çavdar"]'::jsonb,
    79,
    '{"flourHeritage": "Üç kadim tahılın taş değirmende harmanlanması: Kastamonu Siyezi, glütensiz karabuğday ve aromatik çavdar.", "technique": "Fırında kavrulan cevizlerin yağı hamurun lezzetine geçer; 36 saatlik fermantasyonla nemli gözenekli yapı kazanır.", "healthBenefit": "Omega-3 yağ asitleri, karabuğdayın antioksidanları ve çavdarın zengin lifleriyle kalp dostu ve tok tutucu.", "pairingStorage": "Tulum peyniri, eski kaşar veya petek bal ile mükemmel eşleşir."}'::jsonb
),
(
    'prod_kavilca_02',
    'Kavılca & Siyez Çavdarlı',
    'kavilca-siyez-cavdarli',
    'Kars Kavılcası ve Kastamonu Siyezi harmanı. 40 saatlik yavaş fermantasyonla olgunlaştırılmış zengin mineral profili ve doyurucu kıvam.',
    160,
    'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=900&q=85',
    'specialty',
    20,
    800,
    'g',
    true,
    false,
    true,
    true,
    true,
    '["Kavılca Unu", "Siyez Unu", "Taş Değirmen Çavdar", "Su", "Ekşi Maya", "Kaya Tuzu"]'::jsonb,
    '["Kars Kavılca", "Kastamonu Siyez", "Çavdar"]'::jsonb,
    80,
    '{"flourHeritage": "Soğuk dağ iklimine dayanıklı Kars Kavılcası ve dünyanın en kadim buğdayı Siyez taş değirmende harmanlanır.", "technique": "Düşük gluten yapısı nedeniyle hassas yoğrulur. 40 saatlik soğuk fermantasyon süreciyle tahılın yoğun fındıksı aroması açığa çıkarılır.", "healthBenefit": "Çok yüksek lif, düşük glisemik indeks ve zengin B vitamini kompleksi.", "pairingStorage": "Yayık köy tereyağı ve süzme çiçek balı ile kusursuz bir uyum yakalar."}'::jsonb
),
(
    'prod_ceviz_incir_04',
    'Kavrulmuş Cevizli & Dağ İncirli',
    'kavrulmus-cevizli-dag-incirli',
    'Taş fırında kavrulmuş yerli ceviz ve Aydın dağ inciri parçacıklarıyla zenginleştirilmiş özel artisan lezzet. Peynir tabakları için eşsiz.',
    185,
    'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=900&q=85',
    'specialty',
    15,
    850,
    'g',
    true,
    true,
    false,
    true,
    true,
    '["Karakılçık Unu", "Kavrulmuş Yerli Ceviz", "Aydın Dağ İnciri", "Su", "Ekşi Maya", "Tuz"]'::jsonb,
    '["Karakılçık", "Sarı Buğday"]'::jsonb,
    78,
    '{"flourHeritage": "Ege dağlarından güneşte kurutulmuş incirler ve taze kırılmış yerli cevizler fırında hafif kavrularak hamura katlanır.", "technique": "Meyve şekerinin fermantasyonu hızlandırmasını dengelemek için özel sıcaklık kontrolüyle 36 saat mayalandırılır.", "healthBenefit": "Cevizden gelen Omega-3 yağ asitleri ve incirin doğal lifleri ile enerji veren gurme bir ekmektir.", "pairingStorage": "Eski kaşar veya tulum peyniri ile eşleştirildiğinde tatlı-tuzlu dengesiyle büyüleyici bir sofra deneyimi yaratır."}'::jsonb
),
(
    'YGnge5isqk1d4nI4YUx8',
    'Jersey Çiğ Sütü (3 Litre)',
    'jersey-cig-sutu-3-litre',
    'Arı Jersey Çiftliğinden günlük sağılan, yüksek yağ ve A2 protein yapısına sahip, kaymağı üzerinde %100 doğal taze çiğ süt.',
    200,
    'https://firebasestorage.googleapis.com/v0/b/eksimayaliekmekweb.firebasestorage.app/o/product-images%2Fnew%2F1774227424263_promo-milk3l.png.jpg?alt=media&token=b6841382-489e-4d96-b9b8-9d80b302aa13',
    'gurme',
    40,
    3000,
    'ml',
    false,
    true,
    true,
    true,
    true,
    '["%100 Doğal Jersey Çiğ İnek Sütü"]'::jsonb,
    '[]'::jsonb,
    NULL,
    '{"flourHeritage": "Yüksek A2 beta-kazein protein profiline sahip safkan Jersey ırkı ineklerin taze mera sütüdür.", "technique": "El değmeden sağılıp hemen soğuk zincire alınır; pastörize edilmemiştir.", "healthBenefit": "A2 proteini sindirimi kolaylaştırır, laktoz hassasiyeti olanlar için daha konforludur. Çok zengin kalsiyum ve doğal tereyağ kıvamında kaymak içerir.", "pairingStorage": "Kaynatılıp yoğurt mayalandığında taş gibi tutar, kaymağı tatlılarda enfes sonuç verir."}'::jsonb
),
(
    'prod_yogurt_05',
    'Özel Ev Yapımı Doğal Yoğurt',
    'ozel-ev-yapimi-dogal-yogurt',
    'Doğal mera sütünden geleneksel yöntemlerle mayalanmış, katkısız, kıvam artırıcısız, taş gibi tutan hakiki ev yoğurdu.',
    110,
    'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=85',
    'gurme',
    30,
    1000,
    'g',
    false,
    true,
    false,
    true,
    true,
    '["%100 Doğal Mera Çiğ Sütü", "Geleneksel Canlı Yoğurt Mayası"]'::jsonb,
    '[]'::jsonb,
    NULL,
    '{"flourHeritage": "Serbest otlayan hayvanların taze mera sütünden aile tarifimizle katkısız mayalanır.", "technique": "Kaynatıldıktan sonra ideal derecede tülbentlerle sarılarak yavaşça dinlendirilir.", "healthBenefit": "Zengin doğal probiyotik içeriğiyle bağırsak florasını onarır ve bağışıklığı destekler.", "pairingStorage": "Karakılçık ekmeğini kızartıp üzerine yoğurt ve taze tereyağı sürerek tüketebilirsiniz."}'::jsonb
),
(
    'prod_mihalic_07',
    'Hakiki Mihaliç Peyniri',
    'hakiki-mihalic-peyniri',
    'Geleneksel yöntemlerle gözenekli ve tuzlu salamurada olgunlaştırılmış, yoğun lezzetli hakiki sert Mihaliç peyniri.',
    240,
    'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=900&q=85',
    'gurme',
    25,
    400,
    'g',
    false,
    true,
    false,
    true,
    true,
    '["Koyun ve İnek Sütü", "Şirden Mayası", "Kaya Tuzu"]'::jsonb,
    '[]'::jsonb,
    NULL,
    '{"flourHeritage": "Bursa/Balıkesir yöresinin asırlık peynir geleneği. Gözenekli yapısı ve sert dokusuyla bilinir.", "technique": "Taze sütten şirden mayası ile pıhtılaştırılır, haşlanır ve aylarca dinlendirilir.", "healthBenefit": "Yüksek protein ve kalsiyum deposudur.", "pairingStorage": "Tavada ekşi mayalı ekmek üzerine koyup eritildiğinde veya tostta uzayan nefis bir lezzet verir."}'::jsonb
),
(
    'prod_tereyag_09',
    'Yayık Köy Tereyağı',
    'yayik-koy-tereyagi',
    'Doğal mera sütü kaymağından geleneksel yayık yöntemiyle hazırlanmış, katkısız ve yoğun süt kokulu köy tereyağı.',
    190,
    'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=900&q=85',
    'gurme',
    35,
    500,
    'g',
    false,
    false,
    false,
    true,
    true,
    '["Doğal Süt Kaymağı", "Kaya Tuzu"]'::jsonb,
    '[]'::jsonb,
    NULL,
    '{"flourHeritage": "Geleneksel tahta yayıklarda dövülerek üretilen hakiki köy tereyağı.", "technique": "Kaymaktan ayrıştırılıp soğuk pınar suyu ile yıkanarak asitliği alınır.", "healthBenefit": "A, D, E vitaminleri zengini hakiki enerji kaynağıdır.", "pairingStorage": "Fırından yeni çıkmış sıcak ekmeğe sürüldüğünde buram buram süt kokar."}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    description = EXCLUDED.description,
    image_url = EXCLUDED.image_url,
    category = EXCLUDED.category,
    stock = EXCLUDED.stock,
    weight = EXCLUDED.weight,
    weight_unit = EXCLUDED.weight_unit,
    made_to_order = EXCLUDED.made_to_order,
    is_popular = EXCLUDED.is_popular,
    ingredients = EXCLUDED.ingredients,
    flour_types = EXCLUDED.flour_types,
    hydration = EXCLUDED.hydration,
    masterclass = EXCLUDED.masterclass,
    updated_at = NOW();

-- 3. INITIAL PRODUCTION BATCH (Taze Fırın Çıkışı)
INSERT INTO public.production_batches (
    id, product_id, product_name, batch_number, flour_type, hydration, fermentation_hours,
    planned_quantity, baked_quantity, available_stock, status, notes
)
VALUES
    ('BATCH-TAZE-FIRIN', 'sample-ekmek-1', 'Taş Fırın Ekşi Mayalı Köy Ekmeği', 'BATCH-001', 'Taş Değirmen Atalık Buğday', 76, 36, 50, 45, 45, 'baking', 'Sabah 06:00 taş fırın meşe odunu ateşi partisi')
ON CONFLICT (id) DO NOTHING;
