// Mocks generated by Mockito 5.4.5 from annotations
// in eksi_mayali_ekmek_web/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:eksi_mayali_ekmek_web/domain/repositories/i_user_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i2.IUserRepository {
  MockIUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> getUserProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(#getUserProfile, [userId]),
        returnValue: _i3.Future<Map<String, dynamic>>.value(
          <String, dynamic>{},
        ),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> updateUserProfile(
    String? userId,
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#updateUserProfile, [userId, userData]),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateUserAddress(
    String? userId,
    Map<String, dynamic>? addressData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(#updateUserAddress, [userId, addressData]),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> getUserOrders(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(#getUserOrders, [userId]),
        returnValue: _i3.Future<Map<String, dynamic>>.value(
          <String, dynamic>{},
        ),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Stream<_i4.DocumentSnapshot<Object?>> getUserStream(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(#getUserStream, [userId]),
        returnValue: _i3.Stream<_i4.DocumentSnapshot<Object?>>.empty(),
      ) as _i3.Stream<_i4.DocumentSnapshot<Object?>>);

  @override
  _i3.Future<List<_i4.DocumentSnapshot<Object?>>> getAllUsers() =>
      (super.noSuchMethod(
        Invocation.method(#getAllUsers, []),
        returnValue: _i3.Future<List<_i4.DocumentSnapshot<Object?>>>.value(
          <_i4.DocumentSnapshot<Object?>>[],
        ),
      ) as _i3.Future<List<_i4.DocumentSnapshot<Object?>>>);
}
