// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_r1CdLMa3JqtxiqFdsDAF8zAaOE7bH8',
    appId: '1:984417239539:web:544b34c57488722f6a1286',
    messagingSenderId: '984417239539',
    projectId: 'eksimayaliekmekweb',
    authDomain: 'eksimayaliekmekweb.firebaseapp.com',
    storageBucket: 'eksimayaliekmekweb.firebasestorage.app',
    measurementId: 'G-ESX3TRFPBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_savKCBIQcJLiu_UndSk1K5s18IAoMo',
    appId: '1:984417239539:android:70c82a8f88e58a366a1286',
    messagingSenderId: '984417239539',
    projectId: 'eksimayaliekmekweb',
    storageBucket: 'eksimayaliekmekweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY9U0AUiu1UB9_lXakLR4zou87HTZIUnk',
    appId: '1:984417239539:ios:adcee25d0093f3436a1286',
    messagingSenderId: '984417239539',
    projectId: 'eksimayaliekmekweb',
    storageBucket: 'eksimayaliekmekweb.firebasestorage.app',
    iosBundleId: 'com.example.eksiMayaliEkmekWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY9U0AUiu1UB9_lXakLR4zou87HTZIUnk',
    appId: '1:984417239539:ios:adcee25d0093f3436a1286',
    messagingSenderId: '984417239539',
    projectId: 'eksimayaliekmekweb',
    storageBucket: 'eksimayaliekmekweb.firebasestorage.app',
    iosBundleId: 'com.example.eksiMayaliEkmekWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC_r1CdLMa3JqtxiqFdsDAF8zAaOE7bH8',
    appId: '1:984417239539:web:ab5af7a89cdfd01a6a1286',
    messagingSenderId: '984417239539',
    projectId: 'eksimayaliekmekweb',
    authDomain: 'eksimayaliekmekweb.firebaseapp.com',
    storageBucket: 'eksimayaliekmekweb.firebasestorage.app',
    measurementId: 'G-Z9W4QCSY16',
  );
}
